name: Shax Ultimate Hybrid Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v3

      - name: Frontend Build
        run: |
          if [ -d "web" ]; then
            cd web && npm install && npm run build
          else
            echo "Web papkasi topilmadi!"
          fi

      - name: GitHub Pages-ga yuklash
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/build

      - name: Docker Build
        run: |
          if [ -f "Dockerfile" ]; then
            docker build . --file Dockerfile --tag shax:latest
          else
            echo "Dockerfile topilmadi, bu qadam o'tkazildi."
          fi
    
